path = File.expand_path('..', __FILE__)
$:.unshift File.expand_path("#{path}/../ruby/1.9.1/gems/abstract-1.0.0/lib")
$:.unshift File.expand_path("#{path}/../ruby/1.9.1/gems/chunky_png-1.1.2/lib")
$:.unshift File.expand_path("#{path}/../ruby/1.9.1/gems/fssm-0.2.7/lib")
$:.unshift File.expand_path("#{path}/../ruby/1.9.1/gems/sass-3.1.1/lib")
$:.unshift File.expand_path("#{path}/../ruby/1.9.1/gems/compass-0.11.1/lib")
$:.unshift File.expand_path("#{path}/../ruby/1.9.1/gems/daemons-1.1.3/lib")
$:.unshift File.expand_path("#{path}/../ruby/1.9.1/gems/erubis-2.6.6/lib")
$:.unshift File.expand_path("#{path}/../ruby/1.9.1/gems/eventmachine-1.0.0.beta.3-x86-mingw32/lib")
$:.unshift File.expand_path("#{path}/../ruby/1.9.1/gems/extlib-0.9.15/lib")
$:.unshift File.expand_path("#{path}/../ruby/1.9.1/gems/haml-3.1.1/lib")
$:.unshift File.expand_path("#{path}/../ruby/1.9.1/gems/json_pure-1.4.6/lib")
$:.unshift File.expand_path("#{path}/../ruby/1.9.1/gems/rack-1.2.2/lib")
$:.unshift File.expand_path("#{path}/../ruby/1.9.1/gems/thin-1.2.11-x86-mingw32/lib")
$:.unshift File.expand_path("#{path}/../ruby/1.9.1/gems/thor-0.14.6/lib")
$:.unshift File.expand_path("#{path}/../../lib")
$:.unshift File.expand_path("#{path}/../../lib")
$:.unshift File.expand_path("#{path}/../../vendor/chance/lib")
